### ISSUE TITLE
error thrown with specific dataset

### ISSUE THREAD

**Issue by ziqizhang** [ispras/atr4s#4]
I have successfully tested many algorithms on three datasets but one. I suppose this is due to some oddity in the data but I do not know where to look. However perhaps the program can be revised to be more robust to deal with exceptions as such? The command is:

`./gradlew recognize -Pdataset=$corpus -PtopCount=50000 -Pconfig=$configs/Basic.conf -Poutput=$output/Basic.txt`

The config and the corpus can be downloaded here: https://drive.google.com/file/d/0BwMotMkSrggXeGNQVWxna0lrNDQ/view?usp=sharing
, I wonder if you could have a look at this?

the error is:

-------------------------------------------
INFO  GlobalLexica - Loading word clusters
INFO  AbstractNLPDecoder - Loading tokenizer
INFO  AbstractNLPDecoder - Loading part-of-speech tagger
INFO  AbstractNLPDecoder - Loading morphological analyzer
Exception in thread "main" java.nio.charset.MalformedInputException: Input length = 1
        at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.readLine(BufferedReader.java:324)
        at java.io.BufferedReader.readLine(BufferedReader.java:389)
        at scala.io.BufferedSource$BufferedLineIterator.hasNext(BufferedSource.scala:72)
        at scala.collection.Iterator$class.foreach(Iterator.scala:742)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
        at scala.collection.TraversableOnce$class.addString(TraversableOnce.scala:355)
        at scala.collection.AbstractIterator.addString(Iterator.scala:1194)
        at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:321)
        at scala.collection.AbstractIterator.mkString(Iterator.scala:1194)
        at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:323)
        at scala.collection.AbstractIterator.mkString(Iterator.scala:1194)
        at ru.ispras.atr.preprocess.NLPPreprocessor$$anonfun$2.apply(NLPPreprocessor.scala:33)
        at ru.ispras.atr.preprocess.NLPPreprocessor$$anonfun$2.apply(NLPPreprocessor.scala:31)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
        at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
        at ru.ispras.atr.preprocess.NLPPreprocessor$class.preprocess(NLPPreprocessor.scala:31)
        at ru.ispras.atr.preprocess.EmoryNLPPreprocessor.preprocess(EmoryNLPPreprocessor.scala:18)
        at ru.ispras.atr.AutomaticTermsRecognizer.preprocess(AutomaticTermsRecognizer.scala:32)
        at ru.ispras.atr.AutomaticTermsRecognizer.recognize(AutomaticTermsRecognizer.scala:55)
        at ru.ispras.atr.AutomaticTermsRecognizer$.delayedEndpoint$ru$ispras$atr$AutomaticTermsRecognizer$1(AutomaticTermsRecognizer.scala:128)
        at ru.ispras.atr.AutomaticTermsRecognizer$delayedInit$body.apply(AutomaticTermsRecognizer.scala:101)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at ru.ispras.atr.AutomaticTermsRecognizer$.main(AutomaticTermsRecognizer.scala:101)
        at ru.ispras.atr.AutomaticTermsRecognizer.main(AutomaticTermsRecognizer.scala)
:recognize FAILED

FAILURE: Build failed with an exception.

--------------------------------------

**Comment by astrakhantsev** [comment]
Most probably, this dataset has encoding different from UTF-8. I've updated code and Readme a little bit in this regards.

**Comment by ziqizhang** [comment]
Thank you, I think it is working
